version: "3.3"
services:
  lobster_ui:
    build:
      context: frontend
      dockerfile: Dockerfile
    image: cliniq360/lobster-ui:1.9

    container_name: lobster-ui
    ports:
      - "8082:80"
    volumes:
      - ./frontend/src:/app/src
    networks:
      - lobster
    restart: "on-failure"

networks:
  lobster:
    name: lobster-network
