from core.orm_models.hims_appointments import *
from core.orm_models.hims_complaint import *
from core.orm_models.hims_diagnosis import *
from core.orm_models.hims_docDetails import *
from core.orm_models.hims_listOfComplaints import *
from core.orm_models.hims_listOfDiagnosis import *
from core.orm_models.hims_listOfMedicalTests import *
from core.orm_models.hims_listOfMedicines import *
from core.orm_models.hims_listOfPrecautions import *
from core.orm_models.hims_medicalTest import *
from core.orm_models.hims_medicalTestReports import *
from core.orm_models.hims_patientDetails import *
from core.orm_models.hims_precautions import *
from core.orm_models.hims_patientMedicalRecord import *
from core.orm_models.hims_patientVaccinationRecords import *
from core.orm_models.hims_medicines import *
