"""First commit

Revision ID: 2735cad1b4ac
Revises: 
Create Date: 2023-01-16 11:11:41.793478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2735cad1b4ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('email_id', sa.String(), nullable=True),
    sa.Column('base_image_location', sa.String(), nullable=True),
    sa.Column('phone_number', sa.Numeric(), nullable=True),
    sa.Column('user_role', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_id'),
    schema='fmf_schema'
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('owner_id', sa.String(), nullable=True),
    sa.Column('event_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['fmf_schema.users.email_id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='fmf_schema'
    )
    op.create_table('attendees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['fmf_schema.events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['fmf_schema.users.email_id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='fmf_schema'
    )
    op.create_table('images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('s3_location', sa.String(), nullable=True),
    sa.Column('s3_url', sa.Text(), nullable=True),
    sa.Column('valid_upto', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['fmf_schema.events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['fmf_schema.users.email_id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='fmf_schema'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images', schema='fmf_schema')
    op.drop_table('attendees', schema='fmf_schema')
    op.drop_table('events', schema='fmf_schema')
    op.drop_table('users', schema='fmf_schema')
    # ### end Alembic commands ###
