from core.orm_models.hospital_schema.appointments import *
from core.orm_models.hospital_schema.condition import *
from core.orm_models.hospital_schema.currentMedicines import *
from core.orm_models.hospital_schema.diagnosis import *
from core.orm_models.hospital_schema.docDetails import *
from core.orm_models.hospital_schema.examinationFindings import *
from core.orm_models.hospital_schema.labInvestigations import *
from core.orm_models.hospital_schema.medicalHistory import *
from core.orm_models.hospital_schema.medicalTestReports import *
from core.orm_models.hospital_schema.medicines import *
from core.orm_models.hospital_schema.patientDetails import *
from core.orm_models.hospital_schema.patientMedicalDocuments import *
from core.orm_models.hospital_schema.patientMedicalRecord import *
from core.orm_models.hospital_schema.patientVaccinationRecords import *
from core.orm_models.hospital_schema.precautions import *
from core.orm_models.hospital_schema.slots import *
from core.orm_models.hospital_schema.symptoms import *
from core.orm_models.hospital_schema.token import *
from core.orm_models.hospital_schema.users import *
from core.orm_models.hospital_schema.vitals import *
from core.orm_models.hospital_schema.userRoles import *
