export const apis = {
  login: "user/signIn",
  list: "HIP/listAll",
  listPtaient: "patient/listAll",
  registerAadhar: "HID/registration/aadhaar/generateOTP",
  verifyOTPAadhar: "HID/registration/aadhaar/verifyOTP",
  restigerNumber: "registration/mobile/generateOtp",
  registerAadharNumber: "HID/registration/aadhaar/generateMobileOTP",
  verifyOTPNumber: "registration/mobile/verifyOtp",
  registerUser: "patient/register",
  listAllDoctors: "listAllDoctors",
  doctorSlotsDetails: "slots",
  createAppointment: "appointment/create",
  listAppointments: "",
};
